script: "bundle exec rake"

test_script: "bundle exec rake travis"

language: ruby

rvm:
  - 2.1.2

gemfile:
  - Gemfile

services:
  - redis-server

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
